### ISSUE TITLE
[Feat] CI/CD 구축

### ISSUE THREAD

**Issue by its-sky** [MOONSHOT-Team/MOONSHOT-SERVER#10]
## 🛠 Issue

- CI/CD 구축

## 🚀 To-do

- [ ] CI.yml 작성
- [ ] CD.yml 작성
- [ ] deploy.sh 작성
