### ISSUE TITLE
[Refactor] Index 수정 API Objective 추가 및 추가 예외 처리

### ISSUE THREAD

**Issue by its-sky** [MOONSHOT-Team/MOONSHOT-SERVER#110]
## 🛠 Issue

- Objective 생성 시 Idx가 0이 되고 존재하는 Objective Idx를 하나씩 밀기
- Objective Idx 변경 로직 추가
- KeyResult, Task Index Validation(0~2) 비즈니스 로직으로 이동 -> Objective는 사이즈가 10까지라서 하나의 인터페이스를 구현하려면 이동하는 게 맞다고 판단
- IndexController Swagger 설정

## 🚀 To-do

- [x] Objective 생성 시 Idx가 0이 되고 존재하는 Objective Idx를 하나씩 밀기
- [x] Objective Idx 변경 로직 추가
- [x] KeyResult, Task Index Validation(0~2) 비즈니스 로직으로 이동
- [x] IndexController Swagger 설정
