### ISSUE TITLE
[Fix] KR 수정 및 Log 생성 관련 예외 추가

### ISSUE THREAD

**Issue by 0lynny** [MOONSHOT-Team/MOONSHOT-SERVER#138]
## 🛠 Issue

KR 수정 및 Log 생성 관련 예외 추가

## 🚀 To-do

- [ ] KR 시작이 종료시간 보다 빨라야함.  관련 Exception 추가
- [ ] KR 수정 시 target, logContent 둘 중 하나만 입력 되면 Exception 터지게 수정
- [ ] Log 생성 시 logNum, logContent 둘 중 하나만 입력 되면 Exception 터지게 수정
