### ISSUE TITLE
[Fix] 클라이언트 에러 대응

### ISSUE THREAD

**Issue by its-sky** [MOONSHOT-Team/MOONSHOT-SERVER#228]
## 🛠 Issue

- Spring Security 테스트 클라이언트 URL 추가
- Initial Objective 생성 undefined 체킹 추가
- 코드 패키지 잘못 되어 있는거 수정

## 🚀 To-do

- [ ] Spring Security 테스트 클라이언트 URL 추가
- [ ] Initial Objective 생성 undefined 체킹 추가
- [ ] 코드 패키지 잘못 되어 있는거 수정
