### ISSUE TITLE
[Chore] KR 상세 조회 ResponseDto 및 달성 ResponseDto 수정

### ISSUE THREAD

**Issue by 0lynny** [MOONSHOT-Team/MOONSHOT-SERVER#60]
## 🛠 Issue

 KR 상세 조회 ResponseDto 수정

## 🚀 To-do

- [ ] ResponseDto 수정 ("descriptionBefore" , "target" ,"descriptionAfter") 추가
- [ ] KR 상세 조회 title 설정 시 NumberFormat 추가 (1,000건 -> 20,000건)
- [ ] 달성 ResponseDto에 objectiveId 추가
