### ISSUE TITLE
[Feat] 히스토리 조회 API 구현

### ISSUE THREAD

**Issue by its-sky** [MOONSHOT-Team/MOONSHOT-SERVER#61]
## 🛠 Issue

히스토리 조회 API 구현

## 🚀 To-do

- [ ] 히스토리 조회 API 구현
- [ ] Mybatis 동적 쿼리 구현
- [ ] 페이징일지 무한 스크롤일지 정하기
