### ISSUE TITLE
[Fix] KR, Log 관련 Validation 및 Exception 수정

### ISSUE THREAD

**Issue by 0lynny** [MOONSHOT-Team/MOONSHOT-SERVER#75]
## 🛠 Issue

 KR, Log 관련 Validation 및 Exception 수정

## 🚀 To-do

- [x] KR target 0도 가능하도록 수정
- [x] Log logNum 0가능하도록 수정
- [x] Log logNum 진척상황이 target보다 컸을때 exception 삭제
